# Generated by Django 4.2.2 on 2023-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="birth_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
