# Generated by Django 4.2.2 on 2023-07-03 13:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_useraccount_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
