# Generated by Django 4.2.2 on 2023-10-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_usermessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermessage",
            old_name="message",
            new_name="messages",
        ),
    ]
